// <auto-generated />
using System;
using FirebirdSql.EntityFrameworkCore.Firebird.Metadata;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PeladeirosWeb.Data;

namespace PeladeirosWeb.Migrations
{
    [DbContext(typeof(PeladeirosContext))]
    partial class PeladeirosContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Fb:ValueGenerationStrategy", FbValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 31);

            modelBuilder.Entity("PeladeirosWeb.Models.Cidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Fb:ValueGenerationStrategy", FbValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CidadeNome")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)")
                        .HasMaxLength(50);

                    b.Property<string>("UF")
                        .IsRequired()
                        .HasColumnType("VARCHAR(2)")
                        .HasMaxLength(2);

                    b.HasKey("Id");

                    b.ToTable("Cidade");
                });

            modelBuilder.Entity("PeladeirosWeb.Models.Mensalidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Fb:ValueGenerationStrategy", FbValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DatPgto")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("Obs")
                        .HasColumnType("VARCHAR(1000)")
                        .HasMaxLength(1000);

                    b.Property<int>("PeladeiroId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ValorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PeladeiroId");

                    b.HasIndex("ValorId");

                    b.ToTable("Mensalidade");
                });

            modelBuilder.Entity("PeladeirosWeb.Models.Peladeiro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Fb:ValueGenerationStrategy", FbValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("VARCHAR(14)")
                        .HasMaxLength(14);

                    b.Property<string>("Celular")
                        .HasColumnType("VARCHAR(10)")
                        .HasMaxLength(10);

                    b.Property<int>("CidadeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DatCadastro")
                        .HasColumnType("TIMESTAMP");

                    b.Property<DateTime>("DatInativo")
                        .HasColumnType("TIMESTAMP");

                    b.Property<DateTime>("DatNascimento")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("Email")
                        .HasColumnType("VARCHAR(30)")
                        .HasMaxLength(30);

                    b.Property<string>("Endereço")
                        .HasColumnType("VARCHAR(50)")
                        .HasMaxLength(50);

                    b.Property<byte[]>("Foto")
                        .HasColumnType("BLOB SUB_TYPE BINARY");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("VARCHAR(30)")
                        .HasMaxLength(30);

                    b.Property<string>("Numero")
                        .HasColumnType("VARCHAR(10)")
                        .HasMaxLength(10);

                    b.Property<string>("Observacao")
                        .HasColumnType("VARCHAR(1000)")
                        .HasMaxLength(1000);

                    b.Property<string>("Telefone")
                        .HasColumnType("VARCHAR(9)")
                        .HasMaxLength(9);

                    b.HasKey("Id");

                    b.HasIndex("CidadeId");

                    b.ToTable("Peladeiro");
                });

            modelBuilder.Entity("PeladeirosWeb.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Fb:ValueGenerationStrategy", FbValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DatCadastro")
                        .HasColumnType("TIMESTAMP");

                    b.Property<DateTime>("DatInativo")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("VARCHAR(30)")
                        .HasMaxLength(30);

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("VARCHAR(8)")
                        .HasMaxLength(8);

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("PeladeirosWeb.Models.Valor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Fb:ValueGenerationStrategy", FbValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Ano")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mes")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Val")
                        .HasColumnType("DOUBLE PRECISION");

                    b.HasKey("Id");

                    b.ToTable("Valor");
                });

            modelBuilder.Entity("PeladeirosWeb.Models.Mensalidade", b =>
                {
                    b.HasOne("PeladeirosWeb.Models.Peladeiro", "Peladeiro")
                        .WithMany("Mensalidades")
                        .HasForeignKey("PeladeiroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PeladeirosWeb.Models.Valor", "Valor")
                        .WithMany()
                        .HasForeignKey("ValorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PeladeirosWeb.Models.Peladeiro", b =>
                {
                    b.HasOne("PeladeirosWeb.Models.Cidade", "Cidade")
                        .WithMany()
                        .HasForeignKey("CidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
